# Generated by Django 5.1.4 on 2024-12-15 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прозвище')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True, verbose_name='Пол')),
                ('phone_number_1', models.CharField(max_length=20, unique=True, verbose_name='Телефон 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон 2')),
            ],
            options={
                'verbose_name': 'Личность',
                'verbose_name_plural': 'Личности',
                'indexes': [models.Index(fields=['first_name'], name='users_perso_first_n_e190eb_idx'), models.Index(fields=['last_name'], name='users_perso_last_na_e2fd14_idx')],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'phone_number_1'), name='unique_person')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('system_user', models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Сотрудник')], max_length=50, verbose_name='Тип системного пользователя')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'indexes': [models.Index(fields=['system_user'], name='users_role_system__a6817c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('g', 'Государственный'), ('b', 'Бизнес'), ('f', 'Физическое лицо')], max_length=1, verbose_name='Тип клиента')),
                ('fin_account', models.IntegerField(blank=True, null=True, verbose_name='Финансовый аккаунт')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.person', verbose_name='Личность')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'indexes': [models.Index(fields=['type'], name='users_clien_type_af39c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.person', verbose_name='Личность')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'indexes': [models.Index(fields=['role'], name='users_emplo_role_id_f5d7ed_idx')],
            },
        ),
    ]
