# Generated by Django 5.1.4 on 2024-12-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
    ]
