# Generated by Django 5.1.4 on 2024-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='transaction',
            field=models.CharField(max_length=100, unique=True, verbose_name='Счет фактура'),
        ),
    ]
