# Generated by Django 5.1.4 on 2024-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('apartment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('entrance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъезд')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('doorphone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Домофон')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
