# Generated by Django 5.1.4 on 2024-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_doorphone_location_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='location',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='location',
            name='landmark',
            field=models.CharField(blank=True, default='Нет', max_length=100, null=True, verbose_name='Ориентир'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
