# Generated by Django 5.1.4 on 2024-12-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_apartment_alter_location_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='location',
            name='entrance',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Этаж'),
        ),
    ]
