# Generated by Django 5.1.4 on 2024-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_apartment_alter_location_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='location',
            name='entrance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
