# Generated by Django 5.1.4 on 2024-12-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagehistory',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='stage',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_stages', to='users.employee', verbose_name='Ответственный сотрудник'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала этапа'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Приоритет этапа'),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
