# Generated by Django 5.1.4 on 2024-12-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_stagehistory_performed_by_stage_performed_by_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_histories', to='users.employee', verbose_name='Ответственный сотрудник'),
        ),
    ]
