# Generated by Django 5.1.4 on 2024-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_stage_performed_by_stagehistory_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ads_info',
            field=models.CharField(choices=[('friend', 'От знакомого'), ('web', 'Сайт '), ('instagram', 'Инстаграм'), ('facebook', 'Фейсбук'), ('flyers', 'Флаеры'), ('banners', 'Наружная реклама'), ('partners', 'Партнеры'), ('client', 'Клиент')], default='new', max_length=50, verbose_name='Откуда узнал'),
        ),
    ]
