# Generated by Django 5.1.4 on 2024-12-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_tickets_tic_assigne_723acc_idx_and_more'),
        ('users', '0003_rename_sex_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='users.role', verbose_name='Роль'),
        ),
    ]
