# Generated by Django 5.1.4 on 2024-12-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('tickets', '0006_stage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='locations.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ads_info',
            field=models.CharField(choices=[('friend', 'От знакомого'), ('web', 'Сайт '), ('instagram', 'Инстаграм'), ('facebook', 'Фейсбук'), ('flyers', 'Флаеры'), ('banners', 'Наружная реклама'), ('partners', 'Партнеры'), ('client', 'Клиент')], default='new', max_length=50, verbose_name='Источник рекламы'),
        ),
    ]
