# Generated by Django 5.1.4 on 2024-12-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='measurements/photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Замер',
                'verbose_name_plural': 'Замеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукции')),
                ('type', models.CharField(choices=[('type1', 'Тип 1'), ('type2', 'Тип 2')], max_length=20, verbose_name='Тип продукции')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый')], max_length=20, verbose_name='Цвет продукции')),
                ('material', models.CharField(choices=[('metal', 'Металл'), ('plastic', 'Пластик'), ('wood', 'Дерево')], max_length=20, verbose_name='Материал продукции')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
